# This is a basic workflow to help you get started with Actions

name: CI-test-jobs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      test1:
        type: choice
        description: test1
        options:
          - one
          - two
          - three

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "test" 
        run: |
            echo "its running "
  
  build:
    if: inputs.test1 == 'one'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
