# This is a basic workflow to help you get started with Actions

name: CALLER_WORKFLOW

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, In Celler Workflow
        
  called_workflow:
    uses: ./.github/workflows/CALLED_WORKFLOW.yml
    secrets: 
      my_name: 'shiv'
      


