# This is a basic workflow to help you get started with Actions

name: CALLER_WORKFLOW

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      opt2:
        type: choice
        description: opt2
        options:
          - Yes
          - No
      opt1:
        type: choice
        description: opt1
        options:
          - Yes
          - No
      test:
        type: choice
        description: test
        options:
          - shiv
          - megha
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, In Celler Workflow
        
  called_workflow:
    uses: ./.github/workflows/CALLED_WORKFLOW.yml
    if: (inputs.opt1 == 'true' && inputs.test == 'Shiv') || inputs.opt2 == 'true'
    secrets: 
      my_name: "${{ github.event.inputs.test }}"
      


